
# docker create --name mongodata -v /var/pythia/volumes/mongodata:/data/db busybox
mongo:
  restart: always
  image: mongo:latest
  volumes_from:
      - mongodata
pythia:
  restart: always
  image: jdkizer9/pythia
  links:
    - mongo
  ports:
    - "80:8000"
